### ISSUE TITLE
Add Return Number to point attributes

### ISSUE THREAD

**Issue by mccarthyryanc** [tmontaigu/pylas#1]
Thanks for this module! I love the laz-perf integration and streaming support! Would it be possible to add `return_number` to the point attributes?

For example `lasinfo` shows:
```bash
lasinfo -i pylastests/simple.laz
```
```txt
...
number of first returns:        925
number of intermediate returns: 28
number of last returns:         901
number of single returns:       789
overview over number of returns of given pulse: 789 195 71 10 0 0 0
...
```
However, with pylas:
```bash
python -c 'import pylas; print(pylas.open("pylastests/simple.laz").points.dtype.names)'
```
You only get:
```txt
('X', 'Y', 'Z', 'intensity', 'bit_fields', 'raw_classification', 'scan_angle_rank', 'user_data', 'point_source_id', 'gps_time', 'red', 'green', 'blue')
```

**Comment by tmontaigu** [comment]
I'm not sure if I understand correctly,

`return_number` is already accessible  by doing 

``` python
las = pylas.open('simple.las')
las.return_number
```
return_number, number_of_returns, and other fields are 'hidden' in the `bit_fields` because the values are stored on less than a byte. Its the same for the raw_classification.

The number of returns that you show with lasinfo can be accessed with `las.header.number_of_points_by_return`

**Comment by mccarthyryanc** [comment]
You are totally right... that's what I get for rushing through my tests :tired_face:

**Comment by tmontaigu** [comment]
It's ok there is no docs 😗
